### ISSUE TITLE
𨶙字的字型多了一筆，像是髒了一樣

### ISSUE THREAD

**Issue by S-Asakoto** [ButTaiwan/iansui#12]
如圖，在月字內像是多了一點，跟中間兩筆混在一起了
![Screenshot_20220424-174644_Samsung Notes](https://user-images.githubusercontent.com/53332894/164970569-85918ebf-a9ac-47ec-a5c2-a687ef9329cf.jpg)

**Comment by ButTaiwan** [comment]
下一版會修掉。不過這個問題有點麻煩，因為原稿是正確的，不知道為什麼輸出 ttf 時出現了本來沒有的點。
