### ISSUE TITLE
建議各版本字體採用相同名稱

### ISSUE THREAD

**Issue by pastfuture777** [ButTaiwan/iansui#14]
建議在更新字體的時候，
檔名不一樣就好了，
安裝後字體名稱讓他都一樣是芫荽體。

不然有些使用者使用的是舊版，有些是新版，
檔案傳輸之間，
就會造成要重新選擇字體。

**Comment by ButTaiwan** [comment]
#5 已經討論過了，當有任何字符寬度調整時，會更改字型名稱，以確保舊版本字型所排出來的文件版面不會跑掉。
