### ISSUE TITLE
希望能新增「炘」、「闓」兩字

### ISSUE THREAD

**Issue by kkkyy0601** [ButTaiwan/iansui#16]
謝謝製作字體的工作人員！
以上兩字皆是人名中會使用的字，學生的名字中有出現，但是字體沒有。

名字中帶「炘」的名人有：藝人 于成炘、臺灣金融先驅 陳炘、東元電機總經理 范炘。
名字中帶「闓」的名人有：臺北榮總醫師 吳禕闓、東海大學經濟系教授 林立闓、臺中教育大學數學教育學系教授 謝闓如

**Comment by ButTaiwan** [comment]
ver 1.000 已補。
