### ISSUE TITLE
音界號"．"顯示位置不正確

### ISSUE THREAD

**Issue by durianboy** [ButTaiwan/iansui#18]
這個符號應該要位於正中間，但在直書中會出現在右上角，橫書中會出現在左下角。

**Comment by ButTaiwan** [comment]
． (U+FF0E) 在 Unicode 定義是全形句點（FULLWIDTH FULL STOP），不是音界號。
音界號（HYPHENATION POINT）應該是 U+2027 的 「‧」。

U+FF0E 在 Windows 系統字型的細明體與標楷是置中，常被誤用為音界號，但就定義而言是個句點，Mac 系統字型就幾乎都放在左下。建議不要使用 U+FF0E，這個符號並沒有明確定義要置中。

**Comment by durianboy** [comment]
剛剛去查了Unicode的定義，的確如此，但是臺灣教育部使用的是U+FF0E，可能要請教育部處理並公告，不然大家都誤用。

**Comment by ButTaiwan** [comment]
之前打交道的經驗是教育部覺得他只管符號要長什麼樣子，要用哪個字碼不是他的業務...。
