### ISSUE TITLE
對 Chrome 的支援

### ISSUE THREAD

**Issue by WillyYeh** [ButTaiwan/iansui#19]
下載的 Iansui094-Regular.ttf 在 Chrome 中似乎沒有作用，
需要另外轉成 woff 格式才會正常。
https://codepen.io/willyyeh/pen/PodzXvJ

**Comment by ShikiSuen** [comment]
今後開這種工單時，請務必附贈螢幕錄影、來佐證你的論點。
不然你只會給專案的維護者們帶來「後院可能起火」的恐慌。

工單是工作現場。哪怕開工單的人對於業務內容而言是外行，
開工單本身也是需要認真準備內容來輔佐自己的觀點與論據的。
這不是我修院他們去吃的會員制餐廳。

**Comment by ButTaiwan** [comment]
> 下載的 Iansui094-Regular.ttf 在 Chrome 中似乎沒有作用，

原因不明，重新匯出一次就可以了。應該是某個特定版本 Glyphs 特有的問題。
預計下一個版本更新時會修復。

**Comment by ButTaiwan** [comment]
已更新 ver 1.000
