### ISSUE TITLE
白話字ê問題

### ISSUE THREAD

**Issue by shiami** [ButTaiwan/iansui#2]
![Screen Shot 2022-01-21 at 9 27 16 AM](https://user-images.githubusercontent.com/301464/150448905-055b1d71-c4f4-4e78-b6e8-5691c7cd4b77.png)

1. 鼻音符號「ⁿ」kám是ài khah細--sió-khóa？（鼻音符號是不是要再小一點？）
2. 「o͘」hit點siuⁿ óa字母，已經liâm chò-hóe。（「o͘」那一點太接近字母，已經黏在一起。）

Kám-siā! 🙏

**Comment by shiami** [comment]
白話字文獻參考資料（Cha̍p-hāng Kóan-kiàn 十項管見 Chhòa Pôe-hóe 蔡培火 1925）：
http://ip194097.ntcu.edu.tw/memory/TGB/data/10hang/10hang_%E9%A0%81%E9%9D%A2_008.png

![10hang_頁面_008](https://user-images.githubusercontent.com/301464/150449665-bda564d0-b1ed-4234-8d56-1e53a701d10b.png)

**Comment by ButTaiwan** [comment]
![image](https://user-images.githubusercontent.com/5418570/150450154-bdb59386-917d-474a-9dc1-2985c7669450.png)

設計的時陣是有刁工共點佮 o 撨予較倚，因為 o͘ 本身是一个母音，莫分傷開較好。
佮恁貼的內文內底 o͘ 是差不多：

![image](https://user-images.githubusercontent.com/5418570/150450223-d546298a-0cb8-4262-b385-846afd5e28f4.png)

雖然是真倚，毋過應該是袂黏做伙才著。 （像標題的 o͘ 留縫遐闊，彼是當時鉛字的技術問題，彼个號數無做 o͘ 字。）
請看覓你敢有揤著假粗體 （B） ？

我會試看覓敢有法度共撨淡薄仔開一寡仔，毋過嘛袂使共頂懸的調號黏鬥陣，試過才會知。

--

![image](https://user-images.githubusercontent.com/5418570/150452031-67fb4fb6-d73b-4575-88bc-86281238a28b.png)

「ⁿ」的問題，仝款照你貼的這張，內底就有兩種無仝大細的「ⁿ」。紅的較細，我做的共青色的彼款差不多。

我的想法是，只要袂看毋著做普通的 n，「ⁿ」是愈大愈好，因為按呢佇細字是才看較清楚。

![image](https://user-images.githubusercontent.com/5418570/150452985-dac00972-e867-4f93-a62d-a0c666838c9e.png)

**Comment by shiami** [comment]
@ButTaiwan 多謝hiah kín回應！

1. 「ⁿ」ê問題確實你講--ê mā是有道理，所pái我chiah提出來討論。Án-ne mā是1款做法。
2. 確實是我ka改做粗--ê chiah án-ne，失覺察--lo͘h，真歹勢。

真多謝你解說，án-ne我先kā問題關--起-ah。
（Tú-chiah有寄付2000-kho͘加減tàu支持，真多謝！）

**Comment by ButTaiwan** [comment]
版本 v0.920 有小可撨過 o͘，應該無進前遐倚矣。
