### ISSUE TITLE
中文直排時標點符號偏移

### ISSUE THREAD

**Issue by WillyYeh** [ButTaiwan/iansui#20]
在中文直排時，
會發現逗號、頓號、句號等標點符號會偏右上角，
不符合台灣的使用習慣。
https://codepen.io/willyyeh/pen/PodzXvJ

**Comment by tonyhuan** [comment]
我連結至你提供的網址，在我電腦中看到的直排標點是置中的，然而實際上芫荽字型的 FE10–FE16 這幾個直排標點的確是非置中。
BUT大很忙，如果你不嫌棄，可以參考我的專案「原俠正楷」，已針對該部分標點做出調整。

**Comment by ButTaiwan** [comment]
這個問題在於，Big5裡真的有FE10–FE16這幾個直排用且置於右上的字符存在。

而因為 Glyphs 命名原則的關係，這幾個字符會是 comma-han.vert 之類的名稱。而會不小心自動產生對應的 GSUB 指令。

因為原則上還是盡量收錄 Big5 有的符號（FE10–FE16），但直排轉換時不要轉到這幾個字符去，在早一點的版本，我有手動修掉 vert 特性，排除這幾個字符了。
但目前最新版本 0.94 好像不小心開啟了自動產生 vrt2 特性。

如果是瀏覽器的話，在CSS關掉 vrt2 特性，只套用 vert，應該會是正常的。

下一個版本會再拿掉自動產生的 vrt2 特性，只是要等一陣子。

**Comment by ButTaiwan** [comment]
已更新 ver 1.000，移除 vrt2 表。
