### ISSUE TITLE
部分帶漢字符號與漢字字型設計不一致

### ISSUE THREAD

**Issue by Des-Magmeta** [ButTaiwan/iansui#24]
如圖，帶圈漢字、帶括號漢字符號與本專案的設計不一致。
![Screenshot_20230521_133824](https://github.com/ButTaiwan/iansui/assets/125174106/21978dca-cfe6-4ce0-ba4b-2077ad96be80)
符號應該改成類似下圖這樣的字型（參考），這樣看上去才會與漢字部分的設計一致。
![Screenshot_20230521_135018](https://github.com/ButTaiwan/iansui/assets/125174106/d8117bed-4d01-4144-b453-444f1802af87)
可以看到，圖中的括弧六、括弧七採用的是標準字型。而芫荽沒有，希望能改下。
感謝But Ko帶來美觀、實用的芫荽！

**Comment by ButTaiwan** [comment]
這些帶圈符號多是日文慣用（沒有Big5碼，少用於中文），所以視為日文，沒有特別處理。
若要考慮此類文字，需要改的符號還有相當多，例如株式會社的合字等...。
