### ISSUE TITLE
字體名稱

### ISSUE THREAD

**Issue by tzchang** [ButTaiwan/iansui#26]
可以出一版字體名稱是全英文的嗎?? 我有一些比較舊又無法更改的app只吃全英文名稱的字體... 我有自己用FontForge改過名字就可以正常使用字體, 但是不知道為什麼GSUB的rule就會失效... 所有標點符號在直排時就不會轉向......

謝謝!

**Comment by ButTaiwan** [comment]
此需求太過於限定特定軟體，傾向不處理。

p.s. TrueType 字型沒有 ROS，語系的定義只有 OS/2 表的 codepage 與 name 表的字型名稱。實務上真的有很多環境就是用字型名稱去推測字型語系的。所以沒有中文名稱就被當作英文字型處理，是有可能的。

**Comment by Alvinst** [comment]
分享一下，我也遇到這樣的問題，但自己用軟體改一改就先頂著用。
[screenshot](https://www.alvinl.cc/images/iansui_issue26.png)

@tzchang 如果您沒有軟體，我把我改好的字體讓您頂著用？

**Comment by 20NE** [comment]
相同問題，如conky，不認字體名稱爲中文

**Comment by 20NE** [comment]
文件名是爲Iansui-Regular.ttf，但字型名稱只有中文名字：
`fc-list | g iansui`
顯示：
`/usr/share/fonts/TTF/Iansui-Regular.ttf: 芫荽:style=Regular`

**Comment by ButTaiwan** [comment]
> 文件名是爲Iansui-Regular.ttf，但字型名稱只有中文名字： `fc-list | g iansui` 顯示： `/usr/share/fonts/TTF/Iansui-Regular.ttf: 芫荽:style=Regular`

看起來又碰到 Glyphs 新版本軟體 bug 了..... （再研究怎麼辦）

**Comment by Alvinst** [comment]
我是在Mac上用FontForge可以依不同語言去設定名字... 如果Ko大需要的話，我可以幫忙做最後加工。擷圖請參考我上面留言

But Ko ***@***.***> 於 2023年6月8日 週四 上午9:58寫道：
