### ISSUE TITLE
關於字形優化的一些建議

### ISSUE THREAD

**Issue by Des-Magmeta** [ButTaiwan/iansui#30]
如題，芫荽的一些字形處理可以稍作優化。比如「蔭」字的「厶」部看著重心不穩，可以參照[霞鶩文楷 GB](https://github.com/lxgw/LxgwWenKaiGB) 的字形優化。

![Contrast.png](https://github.com/ButTaiwan/iansui/assets/125174106/006c9559-741e-4f9b-b6a1-e2d71c1648f1)

**Comment by ButTaiwan** [comment]
歡迎自行fork。
