### ISSUE TITLE
跟您聯繫與請教未來使用芫荽體於APP相關議題

### ISSUE THREAD

**Issue by Clovia-LINE** [ButTaiwan/iansui#33]
HI , 
您好,冒昧先於這裡嘗試留言,
因目前芫荽體有完整的客語漢字特殊字體
想跟您聯繫並請教未來若規劃應用芫荽字體於APP中是否有相關注意事項！

再請您與我聯繫：
LINE ID : cloviawu 

非常感謝！
Cheers,
Clovia

**Comment by ButTaiwan** [comment]
關於授權規定，請參考 https://github.com/ButTaiwan/iansui

**Comment by Clovia-LINE** [comment]
Hi ButTaiwan/iansui Team , 
感謝您的回應，
會主動聯繫主要是因為LINE APP希望能夠協助客語漢字完整呈現於LINE APP溝通過程
幫助台灣客語使用者應用客語溝通！
希望有機會與您們電話或Email進一步聯繫！

目前韓國團隊尚未確認是否有需要, 但有可能會有以下需求：
1.有看到授權條款中可改作, 但若需要以下項目,且非下載檔案可執行,您是否願意提供原始檔案？
2.改作可由您（我們可討論費用）執行, 或您願意授權我方合作設計團隊來做執行？ 


感謝您！
Cheers,
Clovia 


Wu, Wei-Chen
[TW]New Business / Sr. BD Manager

No.333, Rui-Guang Rd., Neihu Dist. Taipei City 114, Taiwan (R.O.C.)
Mobile 0978247372, 0955931130
Email ***@***.*** 
LINE ID : Clovia.LINE



-----Original Message-----

**Comment by Clovia-LINE** [comment]
Hi , 發現信件中圖檔為正常顯示,這裡提供給您！
<img width="794" alt="截圖 2024-04-26 下午1 24 48" src="https://github.com/ButTaiwan/iansui/assets/168076505/5f8133fc-05c5-404d-aedd-ca7d4d4dba48">

**Comment by ButTaiwan** [comment]
應該說公開的 ttf 檔就可以直接修改，改作不用任何授權（依照條款標示出處就好）。

**Comment by Clovia-LINE** [comment]
好的！謝謝您！清楚收到！:) 
非常感謝您的確認！

**Comment by Clovia-LINE** [comment]
Hi 您好！
打擾您了！ 是先前有發信跟您詢問的LINE團隊同仁！
因我們希望未來LINE APP能全面支援客語漢字正常顯示, 因此才會與您聯繫！
目前這個開發計畫有獲得日韓團隊往下執行的資源, 
這裡想跟您請教針對以下Android出現的議題：

1. 不知道您是否有建議改法？ 
2. 若您願意協助修改, 也可告知您專案執行報價喔！ 
  ios版本顯示都正常, 但android 的版本會出現以下黃框現象：
     a ) 行距看起來太窄。 需要調整字體本身的行距。
     b) 句子或單詞的下方區域出現了空白。 需要進行調整以去除不必要的邊距。 
     c) 建議: 此問題可能是由新字體的行高設定或字體本身內建的間距設置所引起的。
          通過調整行距（line height）和字體的內建間距設定，使其行距或內建間距適配兩個平台，可能可以解決問題。
          
         可能要請您測試看看,若不確定作法我來請教作者看看！感謝！ 
      



感謝
Cheers,
Clovia 



Wu, Wei-Chen
[TW]New Business / Sr. BD Manager

No.333, Rui-Guang Rd., Neihu Dist. Taipei City 114, Taiwan (R.O.C.)
Mobile 0978247372, 0955931130
Email ***@***.*** 
LINE ID : Clovia.LINE



-----Original Message-----

**Comment by Aiuanyu** [comment]
@Clovia-LINE 這兩天起享用到你們努力讓 LINE 選用內嵌芫荽體、正常顯示各族語漢字的成果了，承蒙勞瀝多謝！
