### ISSUE TITLE
門的異體字/簡體字 - 门 顯示錯誤 (門的简体字/异体字 - 门 显示错误)

### ISSUE THREAD

**Issue by unknownnumbers** [ButTaiwan/iansui#34]
https://www.zdic.net/hans/%E9%97%A8
门(
![2](https://github.com/ButTaiwan/iansui/assets/28758103/eea1161b-fedb-4cfd-91d3-6de1a657692b)
)
在 iansui 中成了
![1](https://github.com/ButTaiwan/iansui/assets/28758103/79847c7c-7ef6-4c7d-965e-29f728ed834d)

**Comment by ButTaiwan** [comment]
芫荽不支援簡化字。
不在教育部標準字體表範圍內的字原則上都保留日文字形。

**Comment by unknownnumbers** [comment]
> 芫荽不支援簡化字。 不在教育部標準字體表範圍內的字原則上都保留日文字形。

https://www.zdic.net/hans/%E9%96%80
屬 "門" 的異體字. 理論上應該有異體字收錄.
属 "門" 的异体字, 理论上应该有异体字收录.
