### ISSUE TITLE
某些常見字因為編碼而無法以芫荽體呈現

### ISSUE THREAD

**Issue by durianboy** [ButTaiwan/iansui#35]
最近逛網頁時，發現一些很常見的字卻無法以芫荽體呈現，例如：「練」、「理」、「領」、「女」、「北」，經過查詢後發現這些字有多個編碼，而無法以芫荽體呈現的都是位於中日韓相容表意文字的編碼，不知道網頁管理者是不是因為輸入法的關係所以不是用一般的編碼。這個問題應該不算缺漏字，也不確定這個問題是不是Unicode聯盟要處理的，先把這問題提出來讓大家知道。

**Comment by ButTaiwan** [comment]
芫荽並沒有製作相容表意文字，一般的中文字型也不會做。
「相容表意文字」顧名思義就是為了相容既有的其他編碼錯誤的碼位重複，只好在Unicode也畫一區來放這些重複編碼的文字。
Unicode的建議是沒事不要用相容表意文字，這些字真的只是歷史技術債。
（這幾個字來自韓文編碼搞的鬼，韓國編碼規格用漢字讀音來排序，曾經把所有破音字在不同讀音都重複編碼。因為韓文發音的特性，聲母為n、l的漢字很多都變成有兩個編碼。所以一般也只有韓文字型會去造這些字以相容舊編碼。）

刻意不提供相容表意文字，反而容易檢查是不是用錯了字碼。
