### ISSUE TITLE
iOS 產生額外行距 

### ISSUE THREAD

**Issue by Clovia-LINE** [ButTaiwan/iansui#37]
Hi 您好,
這裡是四月份時曾經與您聯繫的APP專案執行窗口
上週有透過先前您的信件回信，但可能沒有成功。
目前我們遇到IOS產生額外行距的議題, 
希望透過專案合作跟您協作解決IOS上出現不正常行距顯示的議題
不曉得是否方便能聯繫或有其他建議方式？

再麻煩您了！
感謝！

**Comment by ButTaiwan** [comment]
由於您透過 E-mail 方式發布在 GitHub 上，圖片都會消失不見，其實我不太懂您碰到的情形。
https://github.com/ButTaiwan/iansui/issues/33

我的聯絡E-mail資訊在個人檔案頁上。
https://github.com/ButTaiwan

**Comment by Clovia-LINE** [comment]
Hi 
非常感謝！
稍晚空檔將信件重新整理發至 ***@***.*** 

感謝您
Cheers,
Clovia 


Wu, Wei-Chen
[TW]New Business / Sr. BD Manager

No.333, Rui-Guang Rd., Neihu Dist. Taipei City 114, Taiwan (R.O.C.)
Mobile 0978247372, 0955931130
Email ***@***.*** 
LINE ID : Clovia.LINE



-----Original Message-----
