### ISSUE TITLE
能否不在字型名稱中添加版本號？

### ISSUE THREAD

**Issue by Ayaginu-Sue** [ButTaiwan/iansui#5]
目前在使用 RIME 輸入法，小狼毫切換字型時需要手動輸入字型全名（芫荽 0.92）。
如果在字型名稱中加入版本號的話，之後每次更新字型版本後都需要重新設置和輸入默認字體名字。所以能否不在字型的名稱中添加版本號？如「芫荽」或「IanSui」。

**Comment by ButTaiwan** [comment]
目前傾向字型名稱加上版本是因為以下兩個原因：

- 每個版本文字寬度可能會改變（例如目前正在製作的 v0.930，有去調整部分台羅拉丁文字的 kerning）。這會讓舊版本已經排好的檔案版面跑掉。（日本專業字型公司的商業字型有個原則是：只要兩台電腦安裝相同名稱的字型，就要得到一樣的顯示效果。這樣才能確保例如設計師排出來的 indd 檔，到印刷廠那裡版面會一致。）
- macOS 的字型 cache 太惱人，重裝同名的字型都要重開機過才能生效。

因為 beta 階段目前還不太能保證新版本不改文字寬度，更新也會比較頻繁，也許等到第一個 stable 版本 (v1.000) 後再考慮會比較好。

**Comment by ButTaiwan** [comment]
> 字型名稱中添加版本號，在其他比如文書軟體使用時，也會有需要大量重新修改的問題，如果寬度確定後希望還是能固定名稱比較理想。

但其實讓各版本獨立存在，主要就是為了文書軟體，這樣編輯舊文件時才不需要擔心版面跑掉的問題。

設計師排完整本書，（例如為了處理孤行、孤字問題）仔細調整過每個換行、換頁位置，只因為裝了字型的新版本，整本書版面跑掉，是很崩潰的。

書籍再刷、再版時，常會需要拿出幾年前的舊 indd 檔案出來改錯字、改文句後重新送印。並且期待開起來的檔案是跟原來一模一樣的，版面不會跑掉。

有些頻繁更新的開源字體不改字型名稱，我是覺得反而無法用在專業書籍排版，風險太大了。

> 說到寬度…有可能出等寬(英數)字版本嗎？

目前無計劃。

**Comment by tonyhuan** [comment]
認同在確定字型寬度前，各版本獨立的確是最安全的作法。
短時間無計劃出等寬(英數)字版本完全可以理解，但希望至少中文與標點符號是同等寬高，排不齊影響實用很可惜。

**Comment by ButTaiwan** [comment]
> 但希望至少中文與標點符號是同等寬高，排不齊影響實用很可惜。

抱歉，我不太懂您說的中文與標點符號不等寬高是哪些標點的問題？

**Comment by xsrvmy** [comment]
> 說到寬度…有可能出等寬字版本嗎？
LXGW有等寬版本，至少 regular weight 應該可以用

**Comment by ButTaiwan** [comment]
因為 ver 0.943 持續使用一年沒有太大問題，目前最新更新的 ver 1.000 版定為穩定版本，移除字型名稱裡的版號。
