### ISSUE TITLE
缺字補字敲碗串 (v0.930)

### ISSUE THREAD

**Issue by ButTaiwan** [ButTaiwan/iansui#6]
因為人力的問題，芫荽盡可能補了我自己收集的繁體中文常用字，但終究是做不了完整的 Big5 之類的範圍（還差幾千字）。所以缺字是難免，尤其是學術領域、古文、歷史名詞、人名等等。

既然是個中文字型，目標還是希望日常生活使用沒有問題。但我可能收集的常用字有所遺漏，也知道自己的名字缺字很難過.... 所以若有需要的缺字，請留言在此串，謝謝。

原則上我會判斷優先製作我認識的字，並斟酌製作我不認識，但看起來像是人名可能常用的字XD

每個建議字，都**請附上使用案例**，解釋這個字在日常用途什麼時候會用到（能附上用到這個字的文章網址更好），方便判斷。人名用字最好可舉例名字有這個字的公眾人物。

無法附上常用案例或經判斷不夠常用者，可能無法優先處理。後來字數太多者我會當作沒看到XD

**Comment by IanHo79** [comment]
奢望Iansui0.93-Regular能夠再增補的漢字，選字的測試環境為：
macOS 10.15.7 + LibreOffice Calc 7.2 + UnicodeChecker.app 1.23 + Iansui0.93-Regular。
以下的選字為「既有詞彙」的其中一字已經收錄於Iansui0.93-Regular，
但同一個詞彙中的另一個字則「還沒有收錄」於Iansui0.93-Regular的選字：
纏綿「悱」惻
https://dict.mini.moe.edu.tw/SearchIndex/word_detail?wordID=D0001061&breadcrumbs=Search_悱_one
「憯」懍
https://dict.revised.moe.edu.tw/dictView.jsp?ID=141931
愧「怍」
https://dict.revised.moe.edu.tw/dictView.jsp?ID=78267
俳「佪」
https://dict.revised.moe.edu.tw/dictView.jsp?ID=22831
「饔」飧
https://dict.revised.moe.edu.tw/dictView.jsp?ID=165908
漫「漶」
https://dict.concised.moe.edu.tw/dictView.jsp?ID=4191
「澴」波
https://dict.revised.moe.edu.tw/dictView.jsp?ID=85640
---
沆「漭」
https://dict.revised.moe.edu.tw/dictView.jsp?ID=82317
國語一字多音審訂表(初稿)
https://language.moe.gov.tw/files/people_files/初稿.pdf
---
「汍」瀾
https://dict.revised.moe.edu.tw/dictView.jsp?ID=161528
「蟿」螽
https://dict.revised.moe.edu.tw/dictView.jsp?ID=99551
「螗」蜩
https://dict.revised.moe.edu.tw/dictView.jsp?ID=51590
「蟊」賊
https://dict.concised.moe.edu.tw/dictView.jsp?ID=4042
颼「飀」
https://dict.revised.moe.edu.tw/dictView.jsp?ID=144280
「髕」骨
https://dict.revised.moe.edu.tw/dictView.jsp?ID=19317
如「骾」在喉
https://dict.concised.moe.edu.tw/dictView.jsp?ID=16595
繈「緥」
https://dict.revised.moe.edu.tw/dictView.jsp?ID=101879
「綈」袍
https://dict.revised.moe.edu.tw/dictView.jsp?ID=52023
「繯」橐
https://dict.revised.moe.edu.tw/dictView.jsp?ID=85736
「紱」冕
https://dict.revised.moe.edu.tw/dictView.jsp?ID=38279
「繾」綣
https://dict.concised.moe.edu.tw/dictView.jsp?ID=25290
「耵」聹
https://dict.concised.moe.edu.tw/dictView.jsp?ID=9084
「抆」拭
https://dict.revised.moe.edu.tw/dictView.jsp?ID=162428
「齮」齕
https://dict.revised.moe.edu.tw/dictView.jsp?ID=150946
「腷」臆
https://dict.revised.moe.edu.tw/dictView.jsp?ID=18050
城「堞」
https://dict.revised.moe.edu.tw/dictView.jsp?ID=124374
---
培「塿」
https://dict.revised.moe.edu.tw/dictView.jsp?ID=23562
國語一字多音審訂表(初稿)
https://language.moe.gov.tw/files/people_files/初稿.pdf
---
垓「埏」
https://dict.revised.moe.edu.tw/dictView.jsp?ID=68454
垠「堮」
https://dict.revised.moe.edu.tw/dictView.jsp?ID=156608
埤「堄」
https://dict.revised.moe.edu.tw/dictView.jsp?ID=17845
壙「埌」
https://dict.revised.moe.edu.tw/dictView.jsp?ID=78672
「圩」堤
https://dict.revised.moe.edu.tw/dictView.jsp?ID=163109
「襝」衽
https://dict.revised.moe.edu.tw/dictView.jsp?ID=64457
褡「褳」
https://dict.revised.moe.edu.tw/dictView.jsp?ID=39594
「襜」褕
https://dict.revised.moe.edu.tw/dictView.jsp?ID=122811
衾「裯」
https://dict.revised.moe.edu.tw/dictView.jsp?ID=101305
惛「眊」
https://dict.revised.moe.edu.tw/dictView.jsp?ID=85956
「跗」蹠
https://dict.revised.moe.edu.tw/dictView.jsp?ID=37835
---
「踧、踖」不安
https://dict.revised.moe.edu.tw/dictView.jsp?ID=142301
教育部《國語一字多音審訂表》國民中小學國語文教科書用字審訂成果初稿.pdf
https://class.tn.edu.tw/modules/tad_web/files.php?WebID=11184
---
鵜「鶘」
https://dict.concised.moe.edu.tw/dictView.jsp?ID=10772
軋「輥」
https://dict.revised.moe.edu.tw/dictView.jsp?ID=114690
輜「軿」
https://dict.revised.moe.edu.tw/dictView.jsp?ID=137305
「薌」萁
https://dict.revised.moe.edu.tw/dictView.jsp?ID=109964
「蒺」藜
https://dict.concised.moe.edu.tw/dictView.jsp?ID=21470
「芣」苡
https://dict.revised.moe.edu.tw/dictView.jsp?ID=34660
甑「箄」
https://dict.revised.moe.edu.tw/dictView.jsp?ID=139130
「讋」服
https://dict.revised.moe.edu.tw/dictView.jsp?ID=114981
窳「楛」
https://dict.revised.moe.edu.tw/dictView.jsp?ID=163854
舔「舕」
https://dict.revised.moe.edu.tw/dictView.jsp?ID=53645
卍「卐」
https://dict.variants.moe.edu.tw/variants/rbt/word_attribute.rbt?quote_code=QjAwMjczLTAwMQ

奢望能收錄的動物相關用字：
「㹴」
https://zh.wikipedia.org/zh-tw/㹴犬
「犰、狳」
https://dict.concised.moe.edu.tw/dictView.jsp?ID=24978
「狺」
https://dict.concised.moe.edu.tw/dictView.jsp?ID=42089
「鼩、鼱」
https://dict.revised.moe.edu.tw/dictView.jsp?ID=103105
「牷」
https://dict.concised.moe.edu.tw/dictView.jsp?ID=26081
「鰣」
https://dict.concised.moe.edu.tw/dictView.jsp?ID=33407

奢望能收錄的「臺灣」地名用字：
阿「坶」坪
https://dict.revised.moe.edu.tw/dictView.jsp?ID=146470

奢望能收錄的「中國大陸」地名用字：
「洧」河
https://dict.revised.moe.edu.tw/dictView.jsp?ID=161137
「洹」水
https://dict.revised.moe.edu.tw/dictView.jsp?ID=85629
「涪」江
https://dict.revised.moe.edu.tw/dictView.jsp?ID=38387
「澠」池
https://dict.revised.moe.edu.tw/dictView.jsp?ID=32015
「沘」
https://dict.revised.moe.edu.tw/dictView.jsp?ID=322
「泜」
https://dict.revised.moe.edu.tw/dictView.jsp?ID=8201
「媯」河
https://dict.concised.moe.edu.tw/dictView.jsp?ID=17201

奢望能收錄的聲音效果用字：
「譆」譆出出
https://dict.revised.moe.edu.tw/dictView.jsp?ID=104586
「喁」喁細語
https://dict.concised.moe.edu.tw/dictView.jsp?ID=44204

奢望能收錄的住宅街區用字：
「衚、衕」
https://dict.concised.moe.edu.tw/dictView.jsp?ID=19935
國語一字多音審訂表(初稿)
https://language.moe.gov.tw/files/people_files/初稿.pdf
---

**Comment by ButTaiwan** [comment]
> 奢望Iansui0.93-Regular能夠再增補的漢字

這些詞我全部不認識。辭典並不是適合的案例，重編國語辭典就收超過萬字，網路上更多數萬字的辭典。
希望有更生活化的使用案例才有意義。

就像辭典裡的阿坶坪無論在地圖、經濟部網站、桃園縣府網站都是阿姆坪。
https://amp.wranb.gov.tw/
https://travel.tycg.gov.tw/zh-tw/Travel/Attraction/1163

芫荽目前的定位是盡可能收錄最少而夠用的漢字。

**Comment by IanHo79** [comment]
可以找到「阿坶坪」字串的網址：
https://ivod.ly.gov.tw/Demand/Speech/100437
https://www.wranb.gov.tw/media/382031/ed000097整合.pdf

**Comment by ButTaiwan** [comment]
> (https://www.wranb.gov.tw/media/382031/ed000097%E6%95%B4%E5%90%88.pdf)

既然這文件裡阿姆坪也遠多於阿坶坪，實務上應該可以認定有姆字就夠了。（補台灣地名用字的原則是：至少找得到公部門路標或門牌吧。）

![image](https://user-images.githubusercontent.com/5418570/152292258-7b9a325a-8f77-498e-b7a0-14d281c688e9.png)

**Comment by CloudeWu** [comment]
想請問有無可能增添「㛢」字？
教育部辭典無收錄此字，但字庫中有收錄：[全字庫 - 㛢](https://www.cns11643.gov.tw/wordView.jsp?ID=994936&SN=&lang=tw)

此字曾出現於藝人的藝名中：[呂「㛢」菱](https://zh.wikipedia.org/wiki/%E5%91%82%E7%A7%80%E9%BD%A1)
Google [僅搜尋繁中](https://www.google.com/search?q="㛢"&lr=lang_zh-TW)亦有 10 頁以上之資料，常見於人名、商家行號的名稱之中。

無論將來是否添加，都感謝您製作此字型，辛苦了！

**Comment by TracyHsuanChiHsu** [comment]
您好
謝謝您製作香菜字體，真心感恩，已斗內

想請問能否增添較常用在姓名上的「瑀」字？
這個字大概在12-20歲的孩子的名字中比較常見到，雖然現在還沒有很高的曝光Google搜尋到的資料也不算太多...
如果能夠製作就太好了，謝謝

**Comment by Taiwania** [comment]
感謝您，是否能夠增加「琋」字？
這也是人名用字，感謝。

**Comment by xup6mp4** [comment]
感謝用心製作香菜字，對低年級教學真的很有幫助！
請求增加「妡」字，用於女子姓名。
不確定是不是常見，但是在教學中偶爾會有連著幾屆都會有碰到名字有這個字的學生。
「妡」：https://dict.variants.moe.edu.tw/variants/rbt/word_attribute.rbt?quote_code=QzAyMDMw

**Comment by ButTaiwan** [comment]
> 請求增加「妡」字

已新增於 0.941 版。

**Comment by yaoku** [comment]
請求增加「箓」字

**Comment by ButTaiwan** [comment]
> 請求增加「箓」字

每個建議字，都請附上使用案例，解釋這個字在日常用途什麼時候會用到（能附上用到這個字的文章網址更好），方便判斷。人名用字最好可舉例名字有這個字的公眾人物。

無法附上常用案例或經判斷不夠常用者，可能無法優先處理。

**Comment by yaoku** [comment]
「箓」字，用在人名，但無公眾人物使用。

**Comment by irenehuang1026** [comment]
請求增加 "灃" 一個字，人名，也蠻常見的，只是目前沒有公眾人物使用。

**Comment by D-D51842** [comment]
請求增加「芠」字，也是人名常見的字!

**Comment by tea-egg-tw** [comment]
請求增加「禕」字，也是人名常見的字!

**Comment by xr2439** [comment]
請求增加「玹」字，常出現於人名，如李玹珠、梁玹種、李鎧玹、鄭在玹

**Comment by lks2024** [comment]
請求增加「吖」字，為粵語常見語氣助詞

**Comment by ButTaiwan** [comment]
以上「灃玗芠禕玹吖」等字已新增於 0.943 版。

「箓」字由於 Big5 與教育部字體表均未收，暫不收錄。

**Comment by TCChen301** [comment]
請求增加「颻」字，千字文其中一字（千字文為歷代書法家抄寫經典），謝謝

**Comment by mickeypei** [comment]
想推薦這個字體給同事，
因為做生態相關工作，
開始遇到一些鳥類相關字會缺字，
希望能增加以下幾個常用鳥類字：
鴴, 鸌, 鳦, 鳱, 鳾, 鳲, 鵟, 鵚, 鵷, 鷚, 鷳, 鷿, 鸊, 鷉, 黦, 鷀, 䴉, 鶹, 鶥, 䳭
非常感謝～～～

**Comment by bird81309** [comment]
希望能新增「温」這個姓氏，教職工作常常要輸入學生名字...全員就缺這個字很可惜

**Comment by ButTaiwan** [comment]
> 希望能新增「温」這個姓氏，教職工作常常要輸入學生名字...全員就缺這個字很可惜

芫荽應該一直都是有「温」字的....

**Comment by bird81309** [comment]
> > 希望氏能新增“溫”這個姓氏，教職工作要經常輸入學生字名……
> 
> 芫荽應該一直有“溫”字的……

原來是我沒更新...更新之後真的有了耶！！謝謝回覆！

**Comment by bird81309** [comment]
希望能新增「宬」

**Comment by S-Asakoto** [comment]
希望能新增「焯」字，這個字指[一種以水煮熟的烹飪技法](https://zh.m.wikipedia.org/zh-tw/%E7%84%AF)，在人名中亦十分常用（例如澳門娛樂公司太陽城主席，俗稱洗米華的[周焯華](https://zh.m.wikipedia.org/zh-hk/%E5%91%A8%E7%84%AF%E8%8F%AF)），故希望優先補上這個字

**Comment by S-Asakoto** [comment]
> ## 奢望Iansui0.93-Regular能夠再增補的漢字，選字的測試環境為：
> macOS 10.15.7 + LibreOffice Calc 7.2 + UnicodeChecker.app 1.23 + Iansui0.93-Regular。
> 以下的選字為「既有詞彙」的其中一字已經收錄於Iansui0.93-Regular，
> 但同一個詞彙中的另一個字則「還沒有收錄」於Iansui0.93-Regular的選字：
> 纏綿「悱」惻
> [https://dict.mini.moe.edu.tw/SearchIndex/word_detail?wordID=D0001061&breadcrumbs=Search_悱_one](https://dict.mini.moe.edu.tw/SearchIndex/word_detail?wordID=D0001061&breadcrumbs=Search_%E6%82%B1_one)
> 「憯」懍
> https://dict.revised.moe.edu.tw/dictView.jsp?ID=141931
> 愧「怍」
> https://dict.revised.moe.edu.tw/dictView.jsp?ID=78267
> 俳「佪」
> https://dict.revised.moe.edu.tw/dictView.jsp?ID=22831
> 「饔」飧
> https://dict.revised.moe.edu.tw/dictView.jsp?ID=165908
> 漫「漶」
> https://dict.concised.moe.edu.tw/dictView.jsp?ID=4191
> 「澴」波
> https://dict.revised.moe.edu.tw/dictView.jsp?ID=85640
> ## 沆「漭」
> https://dict.revised.moe.edu.tw/dictView.jsp?ID=82317
> 國語一字多音審訂表(初稿)
> [https://language.moe.gov.tw/files/people_files/初稿.pdf](https://language.moe.gov.tw/files/people_files/%E5%88%9D%E7%A8%BF.pdf)
> ## 「汍」瀾
> https://dict.revised.moe.edu.tw/dictView.jsp?ID=161528
> 「蟿」螽
> https://dict.revised.moe.edu.tw/dictView.jsp?ID=99551
> 「螗」蜩
> https://dict.revised.moe.edu.tw/dictView.jsp?ID=51590
> 「蟊」賊
> https://dict.concised.moe.edu.tw/dictView.jsp?ID=4042
> 颼「飀」
> https://dict.revised.moe.edu.tw/dictView.jsp?ID=144280
> 「髕」骨
> https://dict.revised.moe.edu.tw/dictView.jsp?ID=19317
> 如「骾」在喉
> https://dict.concised.moe.edu.tw/dictView.jsp?ID=16595
> 繈「緥」
> https://dict.revised.moe.edu.tw/dictView.jsp?ID=101879
> 「綈」袍
> https://dict.revised.moe.edu.tw/dictView.jsp?ID=52023
> 「繯」橐
> https://dict.revised.moe.edu.tw/dictView.jsp?ID=85736
> 「紱」冕
> https://dict.revised.moe.edu.tw/dictView.jsp?ID=38279
> 「繾」綣
> https://dict.concised.moe.edu.tw/dictView.jsp?ID=25290
> 「耵」聹
> https://dict.concised.moe.edu.tw/dictView.jsp?ID=9084
> 「抆」拭
> https://dict.revised.moe.edu.tw/dictView.jsp?ID=162428
> 「齮」齕
> https://dict.revised.moe.edu.tw/dictView.jsp?ID=150946
> 「腷」臆
> https://dict.revised.moe.edu.tw/dictView.jsp?ID=18050
> 城「堞」
> https://dict.revised.moe.edu.tw/dictView.jsp?ID=124374
> ## 培「塿」
> https://dict.revised.moe.edu.tw/dictView.jsp?ID=23562
> 國語一字多音審訂表(初稿)
> [https://language.moe.gov.tw/files/people_files/初稿.pdf](https://language.moe.gov.tw/files/people_files/%E5%88%9D%E7%A8%BF.pdf)
> ## 垓「埏」
> https://dict.revised.moe.edu.tw/dictView.jsp?ID=68454
> 垠「堮」
> https://dict.revised.moe.edu.tw/dictView.jsp?ID=156608
> 埤「堄」
> https://dict.revised.moe.edu.tw/dictView.jsp?ID=17845
> 壙「埌」
> https://dict.revised.moe.edu.tw/dictView.jsp?ID=78672
> 「圩」堤
> https://dict.revised.moe.edu.tw/dictView.jsp?ID=163109
> 「襝」衽
> https://dict.revised.moe.edu.tw/dictView.jsp?ID=64457
> 褡「褳」
> https://dict.revised.moe.edu.tw/dictView.jsp?ID=39594
> 「襜」褕
> https://dict.revised.moe.edu.tw/dictView.jsp?ID=122811
> 衾「裯」
> https://dict.revised.moe.edu.tw/dictView.jsp?ID=101305
> 惛「眊」
> https://dict.revised.moe.edu.tw/dictView.jsp?ID=85956
> 「跗」蹠
> https://dict.revised.moe.edu.tw/dictView.jsp?ID=37835
> ## 「踧、踖」不安
> https://dict.revised.moe.edu.tw/dictView.jsp?ID=142301
> 教育部《國語一字多音審訂表》國民中小學國語文教科書用字審訂成果初稿.pdf
> https://class.tn.edu.tw/modules/tad_web/files.php?WebID=11184
> 鵜「鶘」 https://dict.concised.moe.edu.tw/dictView.jsp?ID=10772 軋「輥」 https://dict.revised.moe.edu.tw/dictView.jsp?ID=114690 輜「軿」 https://dict.revised.moe.edu.tw/dictView.jsp?ID=137305 「薌」萁 https://dict.revised.moe.edu.tw/dictView.jsp?ID=109964 「蒺」藜 https://dict.concised.moe.edu.tw/dictView.jsp?ID=21470 「芣」苡 https://dict.revised.moe.edu.tw/dictView.jsp?ID=34660 甑「箄」 https://dict.revised.moe.edu.tw/dictView.jsp?ID=139130 「讋」服 https://dict.revised.moe.edu.tw/dictView.jsp?ID=114981 窳「楛」 https://dict.revised.moe.edu.tw/dictView.jsp?ID=163854 舔「舕」 https://dict.revised.moe.edu.tw/dictView.jsp?ID=53645 卍「卐」 https://dict.variants.moe.edu.tw/variants/rbt/word_attribute.rbt?quote_code=QjAwMjczLTAwMQ
> 
> 奢望能收錄的動物相關用字： 「㹴」 [https://zh.wikipedia.org/zh-tw/㹴犬](https://zh.wikipedia.org/zh-tw/%E3%B9%B4%E7%8A%AC) 「犰、狳」 https://dict.concised.moe.edu.tw/dictView.jsp?ID=24978 「狺」 https://dict.concised.moe.edu.tw/dictView.jsp?ID=42089 「鼩、鼱」 https://dict.revised.moe.edu.tw/dictView.jsp?ID=103105 「牷」 https://dict.concised.moe.edu.tw/dictView.jsp?ID=26081 「鰣」 https://dict.concised.moe.edu.tw/dictView.jsp?ID=33407
> 
> 奢望能收錄的「臺灣」地名用字： 阿「坶」坪 https://dict.revised.moe.edu.tw/dictView.jsp?ID=146470
> 
> 奢望能收錄的「中國大陸」地名用字： 「洧」河 https://dict.revised.moe.edu.tw/dictView.jsp?ID=161137 「洹」水 https://dict.revised.moe.edu.tw/dictView.jsp?ID=85629 「涪」江 https://dict.revised.moe.edu.tw/dictView.jsp?ID=38387 「澠」池 https://dict.revised.moe.edu.tw/dictView.jsp?ID=32015 「沘」 https://dict.revised.moe.edu.tw/dictView.jsp?ID=322 「泜」 https://dict.revised.moe.edu.tw/dictView.jsp?ID=8201 「媯」河 https://dict.concised.moe.edu.tw/dictView.jsp?ID=17201
> 
> 奢望能收錄的聲音效果用字： 「譆」譆出出 https://dict.revised.moe.edu.tw/dictView.jsp?ID=104586 「喁」喁細語 https://dict.concised.moe.edu.tw/dictView.jsp?ID=44204
> 
> ## 奢望能收錄的住宅街區用字：
> 「衚、衕」
> https://dict.concised.moe.edu.tw/dictView.jsp?ID=19935
> 國語一字多音審訂表(初稿)
> [https://language.moe.gov.tw/files/people_files/初稿.pdf](https://language.moe.gov.tw/files/people_files/%E5%88%9D%E7%A8%BF.pdf)

支持「抆」字，粵語常用

**Comment by xup6mp4** [comment]
確定安裝0.943版
但是「玗」好像還是沒有收錄其中？

**Comment by WILSON-MU** [comment]
請求新增「芓」這個字。
學生的名字用了這個妙字，好多字體都無法正常顯示 QQ

**Comment by MC-Chiang** [comment]
謝謝你提供這麼好的字型，我也各種在跟朋友推廣香菜XD
最近看書剛好看到一個字還沒有包含在0.943版裡面
所以上來許願請求新增 "蘄" 這個字 
https://dict.concised.moe.edu.tw/dictView.jsp?ID=24428&q=1
我同時還有找到有編碼的資料，不知道會不會讓你的功少一點點
https://zh.m.wiktionary.org/zh-hant/%E8%98%84

**Comment by kkkyy0601** [comment]
謝謝製作字體的工作人員！

希望能新增「炘」、「闓」兩字
以上兩字皆是人名中會使用的字，學生的名字中有出現，但是字體沒有。

名字中帶「炘」的名人有：藝人 于成炘、臺灣金融先驅 陳炘、東元電機總經理 范炘。
名字中帶「闓」的名人有：臺北榮總醫師 吳禕闓、東海大學經濟系教授 林立闓、臺中教育大學數學教育學系教授 謝闓如

**Comment by durianboy** [comment]
「𩻸」：𩻸魚堀溪、𩻸魚堀、𩸙仔、𩻸仔挖莊(臺子古名)、𩻸仔港(大港埔古名)
「傕」：李傕、張傕
「𬌗」：𬌗學、𬌗面

**Comment by durianboy** [comment]
> 謝謝你提供這麼好的字型，我也各種在跟朋友推廣香菜XD 最近看書剛好看到一個字還沒有包含在0.943版裡面 所以上來許願請求新增 "蘄" 這個字 https://dict.concised.moe.edu.tw/dictView.jsp?ID=24428&q=1 我同時還有找到有編碼的資料，不知道會不會讓你的功少一點點 https://zh.m.wiktionary.org/zh-hant/%E8%98%84

還有一種臺灣常見植物芙蓉菊又叫蘄艾

**Comment by Eee14** [comment]
請求新增「寯」這字。
另外，我把我的 Firefox 預設字型設定成芫荽時發現 https://zh.wikipedia.org/zh-tw/微軟正黑體#已知問題 裡有幾個還沒有支援到的字，如果可以的話希望也能加上那幾個字。

**Comment by deceit919** [comment]
請求新增「宭」這字。

**Comment by ButTaiwan** [comment]
ver 1.000 已大量補字。
（主要根據 jf當務字集並參考本討論串之需求，但經本人主觀篩選，並非本串所有文字）
