### ISSUE TITLE
請教能推出更粗的字重嗎？

### ISSUE THREAD

**Issue by BlueNightSky** [ButTaiwan/iansui#7]
您好：
雖說本字體已經是以Semibold為基礎修改，但使用起來還是覺得偏細，不知可否推出更粗的字重，我知道可以用軟體自動加粗，我也這麼試過，但自動化顯示效果不是很理想，應該是需要人為修改，如果能推出加粗版就更好了，非常感謝！

**Comment by ButTaiwan** [comment]
正因為軟體自動加粗效果不是很好，人工處理成本更為浩大，上萬字每個字都要改。
這已經不是開源字型能夠負擔的工程了。

ps1. 霞鹜文楷是機械加粗的。

**Comment by BlueNightSky** [comment]
好的，感謝啦，的確個人處理不來，只是稍嫌可惜。
雖說霞鹜文楷是機械加粗，但看作者的說明，似乎還是有一點修正，只是大概也不會是全部，特別糊的處理一下大概吧！
總之，還是很感謝提供此字體！
