### ISSUE TITLE
macOS 下，Slack 無法正確設定字型

### ISSUE THREAD

**Issue by alpha-rudy** [ButTaiwan/iansui#9]
Hi, 你好，謝謝你的 Iansui 字型  ^^

在 macOS 下，無法透過 /slackfont 設定字型 (但發現 Klee One 可以)。

不確定原因，但似乎不是 Slack 的問題。

麻煩看看是否可以修正，謝謝！  ^^

<img width="1440" alt="Screen Shot 2022-02-22 at 9 41 09 AM" src="https://user-images.githubusercontent.com/12744709/155047974-5d75bc7a-a557-4899-ac70-519d98641261.png">

**Comment by ButTaiwan** [comment]
我不知道 slack 是怎麼抓字型名稱的，也沒安裝 slack。
請先試試這些名稱？

* Iansui 0.93
* Iansui 0.93 Regular
* Iansui0.93-Regular
* 芫荽 0.93

**Comment by alpha-rudy** [comment]
I think this is not a big issue. Let's close it.  ^^

**Comment by ButTaiwan** [comment]
我實在找不到原因，猜測是碰到 . 被字串處理切斷了。
不然試試看 'Iansui 0.93' （加引號）？

**Comment by alpha-rudy** [comment]
嗯嗯，我試了加單引號 (') 或 雙引號 (") 都無法設定。不過，我覺得原因不明，不容易查，目前這樣已經很好了。謝謝喔！  ^^

**Comment by alpha-rudy** [comment]
Wow, super! It works!  :D

<img width="708" alt="Screen Shot 2022-02-24 at 10 00 17 AM" src="https://user-images.githubusercontent.com/12744709/155456443-54381ced-de3e-4e1c-8835-f571d77a0b30.png">

**Comment by ButTaiwan** [comment]
所以原因真的單純是 slack 不喜歡名稱裡有個點…

**Comment by alpha-rudy** [comment]
的確是蠻難理解的  XD
